---
- name: restart fluentd
  service:
    name: td-agent
    state: restarted

- name: reload systemd
  systemd:
    daemon_reload: true

- name: restart vector
  service:
    name: vector
    state: restarted
