---
# DataCollection group defaults

collection_tool: fluentd  # fluentd, vector, filebeat

fluentd_listen_port: 24224
fluentd_listen_bind: "0.0.0.0"

# Buffer settings
fluentd_buffer_type: file
fluentd_buffer_path: /var/log/fluentd/buffer
fluentd_buffer_chunk_limit: 8m
fluentd_buffer_queue_limit: 256
