---
# DataVisualization group defaults

visualization_tool: kibana  # kibana, grafana

# Kibana settings
kibana_port: 5601
kibana_host: "0.0.0.0"

# Grafana settings
grafana_port: 3000
grafana_admin_user: admin
grafana_admin_password: "changeme"
